import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve, dirname } from 'path';
import { existsSync, readFileSync } from 'fs';
import { writeFile } from 'fs/promises';
import { createRequire } from 'module';

/* ── Seed serializer ─────────────────────────────────────────────────────── */

interface SeedNode {
  id: string;
  label: string;
  level: string;
  tier: string;
  parentId: string | null;
  story?: string;
  context?: string;
  x: number;
  y: number;
  [key: string]: unknown;
}

interface SeedEdge {
  id: string;
  sourceAnchorId: string;
  targetAnchorId: string;
  edgeType: string;
  confidence: number;
}

function findHub(node: SeedNode, all: SeedNode[]): string | null {
  let cur: SeedNode | undefined = node;
  while (cur) {
    if (cur.level === 'parts') return cur.id;
    if (!cur.parentId) return null;
    cur = all.find((n) => n.id === cur!.parentId);
  }
  return null;
}

function serializeNode(n: SeedNode): string {
  const parts: string[] = [
    `id: ${JSON.stringify(n.id)}`,
    `label: ${JSON.stringify(n.label)}`,
    `level: ${JSON.stringify(n.level)}`,
    `tier: ${JSON.stringify(n.tier)}`,
    `parentId: ${n.parentId ? JSON.stringify(n.parentId) : 'null'}`,
  ];
  if (n.story) parts.push(`story: ${JSON.stringify(n.story)}`);
  if (n.context) parts.push(`context: ${JSON.stringify(n.context)}`);
  parts.push(`x: ${Math.round(n.x)}, y: ${Math.round(n.y)}`);
  return `  { ${parts.join(', ')} }`;
}

function serializeSeed(nodes: SeedNode[], crossEdges: SeedEdge[]): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Cognitive Map — Seed Data`);
  lines.push(` *`);
  lines.push(` * This file is generated by running /update-map in Claude Code.`);
  lines.push(` * Claude reads your project state and populates this with nodes and edges.`);
  lines.push(` *`);
  lines.push(` * You can also edit it manually.`);
  lines.push(` *`);
  lines.push(` * Hierarchy:  parts (hubs) → aspects (junctions) → points (stops) → stories (markers)`);
  lines.push(` * Tiers:      lt = anchored (validated/complete)  |  st = draft (in progress/uncertain)`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import type { MemoryNode, CrossEdge } from './types';`);
  lines.push(``);
  lines.push(`let _id = 0;`);
  lines.push(`const edgeId = () => \`xe_\${++_id}\`;`);
  lines.push(``);

  // World node
  const world = nodes.find((n) => n.level === 'world');
  const rest = nodes.filter((n) => n.level !== 'world');

  if (world) {
    lines.push(`// ── World root ──────────────────────────────────────────────────────────────`);
    lines.push(``);
    lines.push(`const WORLD: MemoryNode = {`);
    lines.push(`  id: ${JSON.stringify(world.id)}, label: ${JSON.stringify(world.label)}, level: 'world', tier: 'lt',`);
    lines.push(`  parentId: null, x: ${Math.round(world.x)}, y: ${Math.round(world.y)},`);
    lines.push(`};`);
    lines.push(``);
  }

  // Group non-world nodes by hub
  const hubs = rest.filter((n) => n.level === 'parts');
  const hubChildMap = new Map<string, SeedNode[]>();
  const orphans: SeedNode[] = [];

  for (const hub of hubs) hubChildMap.set(hub.id, []);

  for (const node of rest) {
    if (node.level === 'parts') continue;
    const hubId = findHub(node, rest);
    if (hubId && hubChildMap.has(hubId)) {
      hubChildMap.get(hubId)!.push(node);
    } else {
      orphans.push(node);
    }
  }

  // Build nodes array
  lines.push(`export const nodes: MemoryNode[] = [`);
  if (world) lines.push(`  WORLD,`);

  for (const hub of hubs) {
    lines.push(``);
    lines.push(`  // ── ${hub.label} ${'─'.repeat(Math.max(0, 66 - hub.label.length))}──`);
    lines.push(`${serializeNode(hub)},`);
    for (const child of hubChildMap.get(hub.id) ?? []) {
      lines.push(`${serializeNode(child)},`);
    }
  }

  if (orphans.length > 0) {
    lines.push(``);
    lines.push(`  // ── Unmapped ──────────────────────────────────────────────────────────────`);
    for (const node of orphans) {
      lines.push(`${serializeNode(node)},`);
    }
  }

  lines.push(`];`);
  lines.push(``);

  // Cross-edges
  lines.push(`export const crossEdges: CrossEdge[] = [`);
  for (const edge of crossEdges) {
    lines.push(`  { id: edgeId(), sourceAnchorId: ${JSON.stringify(edge.sourceAnchorId)}, targetAnchorId: ${JSON.stringify(edge.targetAnchorId)}, edgeType: ${JSON.stringify(edge.edgeType)}, confidence: ${edge.confidence} },`);
  }
  lines.push(`];`);
  lines.push(``);

  // Summary
  lines.push(`// ${nodes.length} nodes (${hubs.length} hubs), ${crossEdges.length} cross-edges`);
  lines.push(``);

  return lines.join('\n');
}

/* ── DB proxy (optional — uses engine's better-sqlite3 if available) ──── */

function tryOpenDb(root: string): any {
  try {
    const engineDir = resolve(root, '..', 'map-engine');
    const dbPath = process.env.COGMAP_DB_PATH ?? resolve(engineDir, 'data', 'cogmap.db');
    if (!existsSync(dbPath)) return null;

    const req = createRequire(resolve(engineDir, 'package.json'));
    const Database = req('better-sqlite3');
    return new Database(dbPath, { readonly: true });
  } catch {
    return null;
  }
}

/* ── Vite plugin ─────────────────────────────────────────────────────────── */

function cogmapPlugin(): Plugin {
  let root = '';

  return {
    name: 'cogmap',
    configResolved(config) {
      root = config.root;
    },
    configureServer(server) {
      // POST /api/save-seed — serialize and write seed.ts
      server.middlewares.use('/api/save-seed', async (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405;
          res.end('Method not allowed');
          return;
        }

        const chunks: Buffer[] = [];
        for await (const chunk of req) chunks.push(chunk as Buffer);
        const body = JSON.parse(Buffer.concat(chunks).toString());

        const { nodes, crossEdges } = body as { nodes: SeedNode[]; crossEdges: SeedEdge[] };
        const seedPath = resolve(root, 'src', 'seed.ts');
        const content = serializeSeed(nodes, crossEdges);

        try {
          await writeFile(seedPath, content, 'utf-8');
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ ok: true, path: seedPath }));
        } catch (err: any) {
          res.statusCode = 500;
          res.end(JSON.stringify({ ok: false, error: err.message }));
        }
      });

      // GET /api/changelog/:nodeId — node history from SQLite
      server.middlewares.use('/api/changelog', (req, res) => {
        const nodeId = (req.url ?? '').replace(/^\//, '');
        if (!nodeId) {
          res.statusCode = 400;
          res.end(JSON.stringify({ error: 'nodeId required' }));
          return;
        }

        const db = tryOpenDb(root);
        if (!db) {
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ available: false, entries: [] }));
          return;
        }

        try {
          const entries = db.prepare(
            'SELECT * FROM changelog WHERE node_id = ? ORDER BY detected_at DESC LIMIT 50'
          ).all(nodeId);
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ available: true, entries }));
        } catch {
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ available: false, entries: [] }));
        } finally {
          try { db.close(); } catch {}
        }
      });

      // GET /api/facts/:entity — knowledge graph facts from SQLite
      server.middlewares.use('/api/facts', (req, res) => {
        const entity = decodeURIComponent((req.url ?? '').replace(/^\//, ''));
        if (!entity) {
          res.statusCode = 400;
          res.end(JSON.stringify({ error: 'entity required' }));
          return;
        }

        const db = tryOpenDb(root);
        if (!db) {
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ available: false, facts: [] }));
          return;
        }

        try {
          const facts = db.prepare(
            'SELECT * FROM facts WHERE subject = ? OR object = ? ORDER BY created_at DESC LIMIT 50'
          ).all(entity, entity);
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ available: true, facts }));
        } catch {
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ available: false, facts: [] }));
        } finally {
          try { db.close(); } catch {}
        }
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), cogmapPlugin()],
});
