import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import type { MemoryNode } from '../types';

interface Props {
  nodes: MemoryNode[];
  selectedNodeId: string | null;
  onNodeClick: (id: string) => void;
}

function gaussian(x: number, y: number, cx: number, cy: number, sigma: number, amp: number) {
  const dx = x - cx;
  const dy = y - cy;
  return amp * Math.exp(-(dx * dx + dy * dy) / (2 * sigma * sigma));
}

function marchingSquares(
  field: Float32Array,
  W: number,
  H: number,
  threshold: number
): [number, number, number, number][] {
  const segments: [number, number, number, number][] = [];

  function lerp(a: number, b: number, t: number) { return a + (b - a) * t; }
  function interp(vA: number, vB: number, ax: number, ay: number, bx: number, by: number): [number, number] {
    const t = (threshold - vA) / (vB - vA);
    return [lerp(ax, bx, t), lerp(ay, by, t)];
  }

  for (let gy = 0; gy < H - 1; gy++) {
    for (let gx = 0; gx < W - 1; gx++) {
      const tl = field[gy * W + gx];
      const tr = field[gy * W + gx + 1];
      const bl = field[(gy + 1) * W + gx];
      const br = field[(gy + 1) * W + gx + 1];
      const idx = (tl > threshold ? 8 : 0) | (tr > threshold ? 4 : 0) | (br > threshold ? 2 : 0) | (bl > threshold ? 1 : 0);
      if (idx === 0 || idx === 15) continue;
      const top    = () => interp(tl, tr, gx, gy, gx + 1, gy);
      const right  = () => interp(tr, br, gx + 1, gy, gx + 1, gy + 1);
      const bottom = () => interp(bl, br, gx, gy + 1, gx + 1, gy + 1);
      const left   = () => interp(tl, bl, gx, gy, gx, gy + 1);
      const add = (a: [number, number], b: [number, number]) => segments.push([a[0], a[1], b[0], b[1]]);
      switch (idx) {
        case 1: case 14: add(left(), bottom()); break;
        case 2: case 13: add(bottom(), right()); break;
        case 3: case 12: add(left(), right()); break;
        case 4: case 11: add(top(), right()); break;
        case 5:  add(top(), left()); add(bottom(), right()); break;
        case 6: case 9:  add(top(), bottom()); break;
        case 7: case 8:  add(top(), left()); break;
        case 10: add(top(), right()); add(left(), bottom()); break;
      }
    }
  }
  return segments;
}

/**
 * Three.js terrain canvas rendered from MemoryNode positions.
 *
 * - Heightmap generated by summing Gaussian bumps per anchor (lt = taller peak)
 * - Contour lines via marching squares at 16 elevation levels
 * - Spherical markers with stake lines and floating label sprites
 * - Orbit/pan camera with scroll-zoom; click-to-select via raycasting
 */
export default function MapTerrainCanvas({ nodes, selectedNodeId, onNodeClick }: Props) {
  const mountRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;

    const W = mount.clientWidth || 1200;
    const H = mount.clientHeight || 800;

    // ── Renderer ──────────────────────────────────────────────────────────────
    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setSize(W, H);
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setClearColor(0x080c12, 1);
    mount.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x080c12);

    const camera = new THREE.PerspectiveCamera(50, W / H, 1, 8000);

    // ── Heightmap ─────────────────────────────────────────────────────────────
    const GRID = 180;
    const TERRAIN_W = 1200;
    const TERRAIN_D = 900;
    const NUM_CONTOURS = 16;

    const anchors = nodes.filter(n => n.level !== 'world');

    const xs = anchors.map(n => n.x ?? 0);
    const ys = anchors.map(n => n.y ?? 0);
    const minX = xs.length ? Math.min(...xs) : 0;
    const maxX = xs.length ? Math.max(...xs) : 1;
    const minY = ys.length ? Math.min(...ys) : 0;
    const maxY = ys.length ? Math.max(...ys) : 1;

    function toTerrain(nx: number, ny: number): [number, number] {
      const tx = ((nx - minX) / Math.max(maxX - minX, 1) - 0.5) * TERRAIN_W * 0.82;
      const tz = ((ny - minY) / Math.max(maxY - minY, 1) - 0.5) * TERRAIN_D * 0.82;
      return [tx, tz];
    }

    const fieldW = GRID + 1;
    const fieldH = GRID + 1;
    const field = new Float32Array(fieldW * fieldH);
    let maxH = 0;

    for (let gy = 0; gy <= GRID; gy++) {
      for (let gx = 0; gx <= GRID; gx++) {
        const wx = (gx / GRID - 0.5) * TERRAIN_W;
        const wz = (gy / GRID - 0.5) * TERRAIN_D;
        let h = 0;
        for (const a of anchors) {
          const [tx, tz] = toTerrain(a.x ?? 0, a.y ?? 0);
          const amp = a.tier === 'lt' ? 180 : 90;
          const sigma = a.tier === 'lt' ? 140 : 85;
          h += gaussian(wx, wz, tx, tz, sigma, amp);
        }
        field[gy * fieldW + gx] = h;
        if (h > maxH) maxH = h;
      }
    }

    // ── Contour lines in 3D (stacked at elevation) ────────────────────────────
    for (let c = 1; c < NUM_CONTOURS; c++) {
      const threshold = (c / NUM_CONTOURS) * maxH;
      const segs = marchingSquares(field, fieldW, fieldH, threshold);
      if (segs.length === 0) continue;

      const verts: number[] = [];
      for (const [x1, z1, x2, z2] of segs) {
        const wx1 = (x1 / GRID - 0.5) * TERRAIN_W;
        const wz1 = (z1 / GRID - 0.5) * TERRAIN_D;
        const wx2 = (x2 / GRID - 0.5) * TERRAIN_W;
        const wz2 = (z2 / GRID - 0.5) * TERRAIN_D;
        verts.push(wx1, threshold, wz1, wx2, threshold, wz2);
      }

      const t = c / NUM_CONTOURS;
      const r = 0.55 + t * 0.45;
      const g = 0.75 + t * 0.25;
      const b = 1.0;
      const opacity = 0.18 + t * 0.65;

      const geo = new THREE.BufferGeometry();
      geo.setAttribute('position', new THREE.Float32BufferAttribute(verts, 3));
      const mat = new THREE.LineBasicMaterial({ color: new THREE.Color(r, g, b), transparent: true, opacity });
      scene.add(new THREE.LineSegments(geo, mat));
    }

    // ── Markers ───────────────────────────────────────────────────────────────
    const markerGroup = new THREE.Group();
    scene.add(markerGroup);

    const markerMeshes: Array<{ mesh: THREE.Mesh; id: string }> = [];

    for (const anchor of anchors) {
      const [tx, tz] = toTerrain(anchor.x ?? 0, anchor.y ?? 0);

      let peakH = 0;
      for (const a of anchors) {
        const [ax, az] = toTerrain(a.x ?? 0, a.y ?? 0);
        const amp = a.tier === 'lt' ? 180 : 90;
        const sigma = a.tier === 'lt' ? 140 : 85;
        peakH += gaussian(tx, tz, ax, az, sigma, amp);
      }

      const isSelected = anchor.id === selectedNodeId;
      const isLt = anchor.tier === 'lt';
      const baseColor = isSelected ? 0xffdd44 : isLt ? 0xff3311 : 0xff7733;
      const markerH = peakH + (isLt ? 20 : 14);

      const sphere = new THREE.Mesh(
        new THREE.SphereGeometry(isLt ? 9 : 6, 16, 16),
        new THREE.MeshStandardMaterial({
          color: baseColor, emissive: baseColor,
          emissiveIntensity: isSelected ? 3 : 2,
          roughness: 0.15, metalness: 0.05,
        })
      );
      sphere.position.set(tx, markerH, tz);
      sphere.userData = { anchorId: anchor.id };
      markerGroup.add(sphere);
      markerMeshes.push({ mesh: sphere, id: anchor.id });

      const stakeGeo = new THREE.BufferGeometry().setFromPoints([
        new THREE.Vector3(tx, peakH, tz),
        new THREE.Vector3(tx, markerH, tz),
      ]);
      markerGroup.add(new THREE.Line(stakeGeo, new THREE.LineBasicMaterial({ color: baseColor, transparent: true, opacity: 0.5 })));

      const ring = new THREE.Mesh(
        new THREE.RingGeometry(isLt ? 14 : 9, isLt ? 18 : 12, 40),
        new THREE.MeshBasicMaterial({ color: baseColor, transparent: true, opacity: 0.3, side: THREE.DoubleSide })
      );
      ring.rotation.x = -Math.PI / 2;
      ring.position.set(tx, peakH + 1, tz);
      ring.userData = { isHalo: true };
      markerGroup.add(ring);

      const lc = document.createElement('canvas');
      lc.width = 320; lc.height = 52;
      const ctx = lc.getContext('2d')!;
      ctx.clearRect(0, 0, lc.width, lc.height);
      ctx.fillStyle = 'rgba(8,12,18,0.8)';
      ctx.beginPath();
      (ctx as CanvasRenderingContext2D & { roundRect: Function }).roundRect(0, 0, lc.width, lc.height, 5);
      ctx.fill();
      ctx.fillStyle = isSelected ? '#ffdd44' : '#d8eeff';
      ctx.font = `${isLt ? '600' : '500'} 17px Inter, sans-serif`;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(anchor.label.slice(0, 28), lc.width / 2, lc.height / 2);
      const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: new THREE.CanvasTexture(lc), transparent: true }));
      sprite.scale.set(150, 26, 1);
      sprite.position.set(tx, markerH + (isLt ? 32 : 22), tz);
      markerGroup.add(sprite);
    }

    scene.add(new THREE.AmbientLight(0xffffff, 0.5));

    // ── Camera (orbit + pan) ──────────────────────────────────────────────────
    const spherical = { r: 1200, theta: 0.3, phi: 0.9 };
    const panOffset = new THREE.Vector3(0, 0, 0);

    function sphericalToPos() {
      return new THREE.Vector3(
        spherical.r * Math.sin(spherical.phi) * Math.sin(spherical.theta),
        spherical.r * Math.cos(spherical.phi),
        spherical.r * Math.sin(spherical.phi) * Math.cos(spherical.theta),
      );
    }

    camera.position.copy(sphericalToPos());
    camera.lookAt(panOffset);

    let isDragging = false;
    let isRightDrag = false;
    let lastX = 0;
    let lastY = 0;

    function onMouseDown(e: MouseEvent) {
      isDragging = true;
      isRightDrag = e.button === 2;
      lastX = e.clientX;
      lastY = e.clientY;
    }
    function onMouseUp() { isDragging = false; }
    function onMouseMove(e: MouseEvent) {
      if (!isDragging) return;
      const dx = e.clientX - lastX;
      const dy = e.clientY - lastY;
      lastX = e.clientX;
      lastY = e.clientY;

      if (isRightDrag) {
        const camRight = new THREE.Vector3();
        camRight.crossVectors(camera.getWorldDirection(new THREE.Vector3()), camera.up).normalize();
        const camUp = camera.up.clone();
        const speed = spherical.r * 0.0012;
        panOffset.addScaledVector(camRight, -dx * speed);
        panOffset.addScaledVector(camUp, dy * speed);
      } else {
        spherical.theta -= dx * 0.006;
        spherical.phi = Math.max(0.05, Math.min(Math.PI - 0.05, spherical.phi + dy * 0.005));
      }

      camera.position.copy(sphericalToPos()).add(panOffset);
      camera.lookAt(panOffset);
    }
    function onWheel(e: WheelEvent) {
      spherical.r = Math.max(200, Math.min(3500, spherical.r + e.deltaY * 1.1));
      camera.position.copy(sphericalToPos()).add(panOffset);
      camera.lookAt(panOffset);
    }
    function onContextMenu(e: Event) { e.preventDefault(); }

    renderer.domElement.addEventListener('mousedown', onMouseDown);
    window.addEventListener('mouseup', onMouseUp);
    renderer.domElement.addEventListener('mousemove', onMouseMove);
    renderer.domElement.addEventListener('wheel', onWheel, { passive: true });
    renderer.domElement.addEventListener('contextmenu', onContextMenu);

    // ── Click → raycasting ────────────────────────────────────────────────────
    const raycaster = new THREE.Raycaster();
    const mouse = new THREE.Vector2();
    let mouseDownPos = { x: 0, y: 0 };

    renderer.domElement.addEventListener('mousedown', (e) => { mouseDownPos = { x: e.clientX, y: e.clientY }; });
    renderer.domElement.addEventListener('click', (e) => {
      if (Math.abs(e.clientX - mouseDownPos.x) > 4 || Math.abs(e.clientY - mouseDownPos.y) > 4) return;
      const rect = renderer.domElement.getBoundingClientRect();
      mouse.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
      mouse.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(mouse, camera);
      const meshes = markerMeshes.map(m => m.mesh);
      const hits = raycaster.intersectObjects(meshes);
      if (hits.length > 0) {
        const hit = hits[0].object;
        if (hit.userData?.anchorId) onNodeClick(hit.userData.anchorId);
      }
    });

    // ── HUD overlay ───────────────────────────────────────────────────────────
    const hud = document.createElement('canvas');
    hud.style.cssText = 'position:absolute;top:0;left:0;pointer-events:none';
    hud.width = W; hud.height = H;
    mount.style.position = 'relative';
    mount.appendChild(hud);
    const hctx = hud.getContext('2d')!;

    function drawHud() {
      hctx.clearRect(0, 0, hud.width, hud.height);
      const b = 18, bl = 28;
      hctx.strokeStyle = 'rgba(80,160,255,0.45)';
      hctx.lineWidth = 1.5;
      for (const [cx, cy, sx, sy] of [[b,b,1,1],[hud.width-b,b,-1,1],[b,hud.height-b,1,-1],[hud.width-b,hud.height-b,-1,-1]] as const) {
        hctx.beginPath(); hctx.moveTo(cx,cy); hctx.lineTo(cx+sx*bl,cy); hctx.stroke();
        hctx.beginPath(); hctx.moveTo(cx,cy); hctx.lineTo(cx,cy+sy*bl); hctx.stroke();
      }
      hctx.font = '11px "Courier New", monospace';
      hctx.fillStyle = 'rgba(80,160,255,0.65)';
      hctx.fillText('MEMORY TERRAIN  //  MAP VIEW', b+6, b+18);
      hctx.fillStyle = 'rgba(80,160,255,0.38)';
      hctx.fillText(`${anchors.length} ANCHORS  ·  DRAG ORBIT  ·  RIGHT-DRAG PAN  ·  SCROLL ZOOM`, b+6, b+33);
      const az = ((spherical.theta * 180) / Math.PI).toFixed(1);
      const el = ((spherical.phi  * 180) / Math.PI).toFixed(1);
      hctx.fillStyle = 'rgba(80,160,255,0.45)';
      hctx.textAlign = 'right';
      hctx.fillText(`AZ ${az}°  EL ${el}°  R ${spherical.r.toFixed(0)}`, hud.width-b-6, hud.height-b-6);
      hctx.textAlign = 'left';
    }

    // ── Animation loop ────────────────────────────────────────────────────────
    let frameId: number;
    let t = 0;

    function animate() {
      frameId = requestAnimationFrame(animate);
      t += 0.016;
      markerGroup.children.forEach(child => {
        if (child.userData?.isHalo) {
          (child as THREE.Mesh).material instanceof THREE.MeshBasicMaterial &&
            ((child as THREE.Mesh).material as THREE.MeshBasicMaterial).opacity !== undefined
            ? ((child as THREE.Mesh).material as THREE.MeshBasicMaterial).opacity = 0.12 + 0.22 * (0.5 + 0.5 * Math.sin(t * 2.5))
            : null;
        }
      });
      drawHud();
      renderer.render(scene, camera);
    }
    animate();

    // ── Resize ────────────────────────────────────────────────────────────────
    const obs = new ResizeObserver(() => {
      const nW = mount.clientWidth, nH = mount.clientHeight;
      renderer.setSize(nW, nH);
      camera.aspect = nW / nH;
      camera.updateProjectionMatrix();
      hud.width = nW; hud.height = nH;
    });
    obs.observe(mount);

    return () => {
      cancelAnimationFrame(frameId);
      obs.disconnect();
      renderer.domElement.removeEventListener('contextmenu', onContextMenu);
      window.removeEventListener('mouseup', onMouseUp);
      renderer.dispose();
      if (mount.contains(renderer.domElement)) mount.removeChild(renderer.domElement);
      if (mount.contains(hud)) mount.removeChild(hud);
    };
  }, [nodes, selectedNodeId]);

  return (
    <div
      ref={mountRef}
      style={{ width: '100%', height: '100%', background: '#080c12', cursor: 'grab' }}
    />
  );
}
