/**
 * Cognitive Map — Seed Data
 *
 * This file is generated by running /update-map in Claude Code.
 * Claude reads your project state and populates this with nodes and edges.
 *
 * You can also edit it manually.
 *
 * Hierarchy:  parts (hubs) → aspects (junctions) → points (stops) → stories (markers)
 * Tiers:      lt = anchored (validated/complete)  |  st = draft (in progress/uncertain)
 */

import type { MemoryNode, CrossEdge } from './types';

// ── Helpers ──────────────────────────────────────────────────────────────────

let _id = 0;
const edgeId = () => `xe_${++_id}`;

// ── World root (required) ────────────────────────────────────────────────────

const WORLD: MemoryNode = {
  id: '__overview_world__', label: 'Project', level: 'world', tier: 'lt',
  parentId: null, x: 600, y: 450,
};

// ═══════════════════════════════════════════════════════════════════════════════
//  Define your hubs (parts), junctions (aspects), stops (points), and
//  markers (stories) below. Run /update-map to have Claude generate them
//  from your project state.
//
//  Example hub:
//
//  const example: MemoryNode = {
//    id: 'example', label: 'Example Hub', level: 'parts', tier: 'lt',
//    parentId: '__overview_world__',
//    story: 'Description shown when you click this node.',
//    x: 400, y: 300,
//  };
//
//  const example_child: MemoryNode = {
//    id: 'example_child', label: 'A Junction', level: 'aspects', tier: 'st',
//    parentId: 'example',
//    story: 'Junctions group related stops under a hub.',
//    x: 400, y: 250,
//  };
// ═══════════════════════════════════════════════════════════════════════════════

export const nodes: MemoryNode[] = [
  WORLD,
  // Run /update-map to populate
];

export const crossEdges: CrossEdge[] = [
  // Run /update-map to populate
];
